"""What the browser login makes of an Instagram web page, from its URL and visible text.

Samples are what Instagram showed (06.10, en-US) or its known wording; no live Instagram.
"""

import pytest

from ig_connector.instagram.weblogin.pages import Page, recognise

IG = "https://www.instagram.com"


@pytest.mark.parametrize(
    ("url", "text"),
    [
        (
            f"{IG}/accounts/login/",
            "Instagram Phone number, username, or email Password Log in Forgot password?",
        ),
        (f"{IG}/", "Log into Instagram Mobile number, username or email Password Log in Forgot password?"),
    ],
)
def test_login_form(url: str, text: str) -> None:
    assert recognise(url, text) is Page.LOGIN_FORM


@pytest.mark.parametrize(
    ("url", "text"),
    [
        # seen live 06.10, account 2
        (
            f"{IG}/accounts/login/two_step_verification/?next=%2F",
            "Go to your authentication app Enter the 6-digit code for this account from the "
            "two-factor authentication app that you set up (such as Duo Mobile or Google "
            "Authenticator). Code Continue Try another way",
        ),
        (
            f"{IG}/accounts/login/two_factor?next=%2F",
            "Two-Factor Authentication Enter the code from your authentication app Confirm",
        ),
        (
            f"{IG}/two_factor/",
            "Enter the 6-digit code generated by your code generator app. Security code Confirm",
        ),
    ],
)
def test_two_factor_by_authentication_app(url: str, text: str) -> None:
    assert recognise(url, text) is Page.TWO_FACTOR_APP


@pytest.mark.parametrize(
    ("url", "text"),
    [
        (
            f"{IG}/accounts/login/two_step_verification/",
            "Check your text messages Enter the 6-digit code we sent to your number ending in 42. Code Continue",
        ),
        (
            f"{IG}/accounts/login/two_factor",
            "Enter the security code we sent to your WhatsApp account. Confirm",
        ),
        (
            f"{IG}/accounts/login/two_step_verification/",
            "Check your email Enter the code we sent to a***@gmail.com",
        ),
    ],
)
def test_two_factor_by_sms_whatsapp_or_email_is_not_ours(url: str, text: str) -> None:
    assert recognise(url, text) is Page.TWO_FACTOR_OTHER


@pytest.mark.parametrize(
    ("url", "text"),
    [
        # seen live 06.10, accounts 3 and 4
        (
            f"{IG}/accounts/login/",
            "The login information you entered is incorrect. Find your account and log in.",
        ),
        (f"{IG}/accounts/login/", "Sorry, your password was incorrect. Please double-check your password."),
        (
            f"{IG}/accounts/login/",
            "The username you entered doesn't belong to an account. Please check your username and try again.",
        ),
        (
            f"{IG}/accounts/login/two_step_verification/",
            "This code isn't valid. Check the code and try again.",
        ),
        (f"{IG}/accounts/login/two_factor", "Please check the security code and try again."),
    ],
)
def test_wrong_login_password_or_code(url: str, text: str) -> None:
    assert recognise(url, text) is Page.WRONG_CREDENTIALS


@pytest.mark.parametrize(
    ("url", "text"),
    [
        (f"{IG}/challenge/action/AXH?next=%2F", "Help us confirm it's you. Send security code"),
        (f"{IG}/challenge/?next=/", "We Detected An Unusual Login Attempt"),
        (f"{IG}/accounts/suspended/?next=%2F", "We suspended your account"),
        (f"{IG}/accounts/disabled/", "Your account has been disabled"),
        (f"{IG}/checkpoint/", "Confirm it's you"),
        (f"{IG}/auth_platform/codeentry/?apc=x", "Check your email Enter the code we sent"),
        (f"{IG}/accounts/login/", "Help us confirm you're human. I'm not a robot"),
        (f"{IG}/accounts/login/", "Suspicious Login Attempt We detected an unusual login attempt"),
    ],
)
def test_checks_we_cannot_pass(url: str, text: str) -> None:
    assert recognise(url, text) is Page.CHALLENGE


@pytest.mark.parametrize(
    "text",
    [
        "Please wait a few minutes before you try again.",
        "Too many login attempts. Try again later.",
    ],
)
def test_rate_limited(text: str) -> None:
    assert recognise(f"{IG}/accounts/login/", text) is Page.RATE_LIMITED


@pytest.mark.parametrize(
    ("url", "text"),
    [
        (f"{IG}/accounts/onetap/?next=%2F", "Save your login info? Save info Not now"),
        (f"{IG}/some/new/page/", "Something entirely new"),
        ("about:blank", ""),
        # the code page before its text rendered: neither ours nor not ours yet
        (f"{IG}/accounts/login/two_step_verification/?next=%2F", ""),
        (f"{IG}/accounts/login/two_step_verification/", "Loading..."),
    ],
)
def test_anything_else_is_unknown(url: str, text: str) -> None:
    assert recognise(url, text) is Page.UNKNOWN
